In [ ]:
import pandas as pd
f1 = pd.read_csv('movie_info5.csv',usecols=['电影名','时长','评分'])

#选择列 单列 多列
#f1['时长']
f1[['时长','评分']]

In [8]:
#选择行 iloc和loc iloc是不根据索引
f1.iloc[0:3:1]#和切片一样 注意 不包含结束位置
#注意 这里的范围是根据隐藏的第一列：行号选择的 不受索引影响

  电影名      时长  评分
0  滚木  145min  79
1  滚木  173min  80
2  滚木  148min  79

In [15]:

f1.loc['滚木1':'滚木2':1]

Empty DataFrame
Columns: [电影名, 时长, 评分]
Index: []